//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTemplates
    {
        public int FoodTemplateID { get; set; }
        public string Sobhane { get; set; }
        public string Nahar { get; set; }
        public string Asrane { get; set; }
        public string Sham { get; set; }
        public string Tem1 { get; set; }
        public string Tem2 { get; set; }
        public string Tem3 { get; set; }
        public string Tem4 { get; set; }
        public string SobhaneDesc { get; set; }
        public string NaharDesc { get; set; }
        public string AsraneDesc { get; set; }
        public string ShamDesc { get; set; }
        public string Regim { get; set; }
        public Nullable<int> AllCallory { get; set; }
        public string VitaminUsed { get; set; }
        public string TemplateName { get; set; }
    }
}
