//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvView
    {
        public int InvID { get; set; }
        public Nullable<int> InvCount { get; set; }
        public string InvDate { get; set; }
        public string InvEnterDate { get; set; }
        public string InvOutDate { get; set; }
        public string InvDes { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string FullName { get; set; }
        public byte[] UserImage { get; set; }
        public Nullable<byte> UserActive { get; set; }
        public Nullable<byte> UserGender { get; set; }
        public string UserGenderFarsi { get; set; }
        public string UserActiveFarsi { get; set; }
    }
}
