//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMove
    {
        public int ProgramPickerID { get; set; }
        public Nullable<int> ProgramValue { get; set; }
        public string ProgramName { get; set; }
    }
}
