//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MorabiTable_View
    {
        public int MorabiID { get; set; }
        public string MorabiName { get; set; }
        public string MorabiMeliCode { get; set; }
        public string MorabiPhone { get; set; }
        public string MorabiFamily { get; set; }
        public Nullable<byte> MorabiSen { get; set; }
        public Nullable<int> MorabiFinder { get; set; }
        public Nullable<bool> MorabiGender { get; set; }
        public string MorabiUsername { get; set; }
        public string MorabiPassword { get; set; }
        public byte[] MorabiImage { get; set; }
        public string MorabiGymName { get; set; }
    }
}
