//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramList
    {
        public int BarnameID { get; set; }
        public string Run1 { get; set; }
        public string Run2 { get; set; }
        public string Run3 { get; set; }
        public string Run4 { get; set; }
        public string Run6 { get; set; }
        public string Run7 { get; set; }
        public string Run1Desc { get; set; }
        public string Run2Desc { get; set; }
        public string Run3Desc { get; set; }
        public string Run4Desc { get; set; }
        public string Run5Desc { get; set; }
        public string Run6Desc { get; set; }
        public string Run7Desc { get; set; }
        public int Picker { get; set; }
    }
}
