//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vegetablesTable
    {
        public int vegetablesID { get; set; }
        public string vegetablesName { get; set; }
        public Nullable<int> vegetablesCalorie { get; set; }
        public string vegetablesDesc { get; set; }
        public Nullable<int> UserFindID { get; set; }
        public byte[] vegetablesImage { get; set; }
        public string vegetablesVitamin { get; set; }
        public Nullable<int> Finder { get; set; }
    }
}
