//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Users
    {
        public string UserRegTime { get; set; }
        public Nullable<byte> UserShahrie { get; set; }
        public Nullable<byte> UserKarKard { get; set; }
        public Nullable<byte> UserTamrin { get; set; }
        public string userSize { get; set; }
        public string userGhaad { get; set; }
        public string UserDoreKamar { get; set; }
        public string UserDoreBazo { get; set; }
        public string UserDoreSine { get; set; }
        public string HomePhone { get; set; }
        public string UserAddress { get; set; }
        public string CodeMeli { get; set; }
        public Nullable<byte> UserGender { get; set; }
        public Nullable<byte> UserAge { get; set; }
        public Nullable<byte> UserActive { get; set; }
        public string UserPassword { get; set; }
        public string UserTel { get; set; }
        public string UserUserName { get; set; }
        public string UserFamily { get; set; }
        public string UserName { get; set; }
        public Nullable<long> Expr22 { get; set; }
        public Nullable<decimal> UserFactor { get; set; }
        public Nullable<long> UserCharge { get; set; }
        public string UserPostCode { get; set; }
        public string UserGenderFarsi { get; set; }
        public string UserActiveFarsi { get; set; }
        public string UserTamrinFarsi { get; set; }
        public string UserRegDate { get; set; }
        public Nullable<long> UserReCharge { get; set; }
        public byte[] UserImage { get; set; }
        public string UsersKomod { get; set; }
        public int UserID { get; set; }
        public string UserLastCharge { get; set; }
        public string UserEndDate { get; set; }
        public Nullable<bool> UserEstakhr { get; set; }
        public Nullable<bool> UserKhososi { get; set; }
        public Nullable<bool> UserBime { get; set; }
        public Nullable<bool> UserBarnameQazaiy { get; set; }
    }
}
